syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";


message C_LOGIN
{
	string ticket = 1;
}

message S_LOGIN // 로그인 통과 시 해당 유저의 캐릭터 목록과 함께 다시 전송
{
	bool success = 1;
	repeated PlayerInfo players = 2; // 내 캐릭터 목록 묘사
}

message C_ENTER_GAME // 유저가 받은 목록을 통해서 입장할 캐릭터 고르기
{
	uint64 playerIndex = 1;
}

message S_ENTER_GAME
{
	bool success = 1;
	PlayerInfo player = 2;
}

message C_LEAVE_GAME // 퇴장 패킷
{

}

message S_LEAVE_GAME
{
	 
}

message S_SPAWN
{
	repeated ObjectInfo objects = 1;
}

message S_DESPAWN
{
	repeated uint64 objectIds = 1;
}

message C_MOVE // 클라이언트->서버 이동패킷
{
	PositionInfo posInfo = 1;
}

message S_MOVE
{
	uint64 objectId = 1;
	PositionInfo posInfo = 2;
}

message C_CHAT
{
	string msg = 1;
}

message S_CHAT
{
	uint64 objectId = 1;
	string msg = 2;
}

message C_PING
{
}

message S_PONG
{
}