syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";


message C_LOGIN
{
	string ticket = 1;
}

message S_LOGIN // 로그인 통과 시 해당 유저의 캐릭터 목록과 함께 다시 전송
{
	bool success = 1;
	repeated PlayerInfo players = 2; // 내 캐릭터 목록 묘사
}

message C_ENTER_GAME // 유저가 받은 목록을 통해서 입장할 캐릭터 고르기
{
	uint64 playerIndex = 1;
}

message S_ENTER_GAME
{
	bool success = 1;
	PlayerInfo player = 2;
}

message C_LEAVE_GAME // 퇴장 패킷
{

}

message S_LEAVE_GAME
{
	 
}

message S_SPAWN
{
	repeated ObjectInfo objects = 1;
}

message S_DESPAWN
{
	repeated uint64 objectIds = 1;
}

message C_MOVE // 클라이언트->서버 이동패킷
{
	PositionInfo posInfo = 1;
}

message S_MOVE
{
	uint64 objectId = 1;
	PositionInfo posInfo = 2;
}

message C_CHAT
{
	string msg = 1;
}

message S_CHAT
{
	uint64 objectId = 1;
	string msg = 2;
}

message C_PING
{
}

message S_PONG
{
}

// ----------------------
// Phase 3: 임시 시나리오 패킷
// ----------------------

message C_ATTACK // 고블린 사냥 공격 패킷
{
	uint64 targetId = 1;
}

message S_ATTACK
{
	uint64 objectId = 1;
	uint64 targetId = 2;
	bool isKilled = 3; // 사망 여부
}

message S_STATUS_CHANGE // 재화/아이템 변경 알림
{
	uint64 objectId = 1;
	int32 gold = 2; // 변경 후 최종 골드
}

message C_CHECK_MAILBOX // 우편함 수령 요청 (결제 후)
{
	// 우편함은 DB에서 긁어오므로 추가 인자 불필요
}